TrajectoryPlannerROS:
  #world_model: costmap
  #dwa: true
  max_vel_x: 0.5
  min_vel_y: 0.5
  max_rotational_vel: 0.6
  min_in_place_rotational_vel: 0.2

  yaw_goal_tolerance: 3.14
  xy_goal_tolerance: 0.3
  acc_lim_th: 2.2
  acc_lim_x: 0.8
  acc_lim_y: 0.0

  holonomic_robot: true
  update_frequency: 10
  publish_frequency: 10

  sim_time: 2.0
  path_distance_bias: 0.6 # (double, default: 0.6)
  goal_distance_bias: 0.8 # (double, default: 0.8)
  occdist_scale: 0.015 # (double, default: 0.01)
  oscillation_reset_dist: 0.05
  #heading_scoring: true #(bool, default: false)
  #heading_scoring_timestep:1 #(double, default: 0.8)
  #heading_lookahead :0.35 # (double, default: 0.325)


  #path_distance_bias: 10.6 # (double, default: 0.6)
  #goal_distance_bias: 0.8 # (double, default: 0.8)
  #occdist_scale: 0.002 # (double, default: 0.01)
  
  vx_samples: 11
