local_costmap:
  
  map_type: costmap
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 1
  #publish_voxel_map: true


  width: 10.0
  height: 10.0
  resolution: 0.05
  static_map: false
  rolling_window: true

  inflation_radius: 0.476
  cost_scaling_factor: 10.0
  #lethal_cost_threshold: 100
